name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build TokenSignature
        run: dotnet build src /p:CommitID=${{ github.sha }}
      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin\*.nupkg
          if-no-files-found: error
